name: Docker Image CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # - name: Pull latest cache
      #   run: docker pull eoluchile/edx-platform:latest

      - name: Build Open edX Base
        run: docker build . --file .github/build/Dockerfile --target base --tag ghcr.io/eol-uchile/edx-platform:${GITHUB_SHA} --tag ghcr.io/eol-uchile/edx-platform:ironwood

      # - name: Build Open edX Testing version
      #   run: docker build . --file .github/build/Dockerfile --target testing --tag eoluchile/edx-platform:testing

      # - name: Test eol changes
      #   run: |
      #     cd .github/test
      #     docker-compose run lms /openedx/edx-platform/.github/test/tests.sh

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: eolito
          password: ${{ secrets.CR_PAT }}

      - name: Push to ironwood
        if: github.ref == 'refs/heads/eol/ironwood.test'
        run: |
          docker push ghcr.io/eol-uchile/edx-platform:${GITHUB_SHA}
          docker push ghcr.io/eol-uchile/edx-platform:ironwood
